In [1]:
import numpy as np

In [2]:
a=np.random.randn(5)

In [3]:
print(a)

[ 0.1760933  -0.50530961  0.45553547 -1.02826333  0.84948976]


In [4]:
print(a.shape)

(5,)


In [5]:
print(a.T)

[ 0.1760933  -0.50530961  0.45553547 -1.02826333  0.84948976]


In [6]:
print(np.dot(a,a.T))

2.27281754308


In [7]:
b=np.random.randn(5,1)

In [8]:
print(b)

[[ 1.73529739]
 [ 0.93374136]
 [-0.84367216]
 [ 0.73713711]
 [ 1.05608209]]


In [11]:
print(b.shape)

(5, 1)


In [9]:
print(b.T)

[[ 1.73529739  0.93374136 -0.84367216  0.73713711  1.05608209]]


In [10]:
print(np.dot(b,b.T))

[[ 3.01125702  1.62031895 -1.4640221   1.27915211  1.83261649]
 [ 1.62031895  0.87187294 -0.7877716   0.68829541  0.98610753]
 [-1.4640221  -0.7877716   0.71178272 -0.62190206 -0.89098706]
 [ 1.27915211  0.68829541 -0.62190206  0.54337112  0.7784773 ]
 [ 1.83261649  0.98610753 -0.89098706  0.7784773   1.11530938]]


In [12]:
c=np.random.randn(1,5)

In [13]:
print(c)

[[-0.87974038  0.5995107  -0.07486244 -0.32080505  0.6938399 ]]


In [14]:
print(c.shape)

(1, 5)


In [15]:
print(c.T)

[[-0.87974038]
 [ 0.5995107 ]
 [-0.07486244]
 [-0.32080505]
 [ 0.6938399 ]]


In [16]:
print(np.dot(c,c.T))

[[ 1.72329027]]


In [17]:
print(c.T.shape)

(5, 1)


In [26]:
assert((c.shape)==(c.T.shape)),'2'

AssertionError: 2

In [31]:
a=a.reshape((5,1))


In [30]:
print(a)

[[ 0.1760933 ]
 [-0.50530961]
 [ 0.45553547]
 [-1.02826333]
 [ 0.84948976]]


In [32]:
a=a.reshape((1,5))

In [33]:
print(a)

[[ 0.1760933  -0.50530961  0.45553547 -1.02826333  0.84948976]]
